import { expect, test } from '@playwright/test';
import { formatMoney } from '../../apps/web/src/money';

test('simulated dollars remain presentation-only through Learn, failure, history and restart', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start Game', exact: true }).click();
  await expect(page.getByTestId('traffic')).toContainText('100');
  await expect(page.getByTestId('budget')).toHaveText(/^\$74\.\d{1,2}K$/);
  await expect(page.getByTestId('lost-sales')).toHaveText('$0/s');
  await expect(page.getByRole('button', { name: 'Add Cache', exact: true })).toHaveAttribute('title', 'Running: $8K/min when active');
  await expect(page.getByRole('button', { name: 'Add Protected Edge', exact: true })).toHaveAttribute('title', 'Running: $3K/min when active');
  await expect(page.getByRole('button', { name: '+ App capacity', exact: true })).toContainText('$5K/min');
  await page.screenshot({ path: info.outputPath('money-normal.png') });
  await page.getByRole('button', { name: 'ⓘ Learn', exact: true }).click();
  const learn = page.getByRole('dialog');
  await expect(learn).toContainText('not actual Azure prices');
  await expect(learn).toContainText('Cache +$8K/min');
  await expect(learn).not.toContainText(/\bcr\b|\bcredits\b/);
  await page.keyboard.press('Escape');
  await expect(page.getByTestId('traffic')).toContainText('260', { timeout: 35000 });
  await expect(page.getByTestId('lost-sales')).toHaveText('$1,276/s');
  await page.setViewportSize({ width: 844, height: 390 });
  await page.screenshot({ path: info.outputPath('money-loss-landscape.png') });
  const loss = await page.getByTestId('lost-sales').boundingBox();
  const next = await page.getByTestId('next-wave').boundingBox();
  expect(loss!.x + loss!.width).toBeLessThanOrEqual(next!.x);
  await expect(page.getByRole('region', { name: 'Business result' })).toBeVisible({ timeout: 40000 });
  await page.setViewportSize({ width: 1440, height: 900 });
  const result = page.getByRole('region', { name: 'Business result' });
  await result.getByText('Details · decisions, tradeoffs & records', { exact: true }).click();
  const run = await page.evaluate(() => JSON.parse(localStorage.getItem('stack-and-survive.history.balance-0.3.v1')!).runs[0]);
  expect(run.score).toBe(810);
  expect(run.elapsed).toBe(45);
  expect(run.cost).toBeLessThan(75);
  await expect(result).toContainText(formatMoney(run.cost + run.emergencyCost));
  await expect(result).toContainText(formatMoney(run.nbv));
  await expect(result).not.toContainText(/\bcr\b|\bcredits\b/);
  await page.screenshot({ path: info.outputPath('money-result.png') });
  await result.getByRole('button', { name: 'Play again', exact: true }).click();
  await page.getByRole('button', { name: 'Start Game', exact: true }).click();
  await expect(page.getByTestId('traffic')).toContainText('100');
  await expect(page.getByTestId('budget')).toHaveText(/^\$74\.\d{1,2}K$/);
  expect(errors).toEqual([]);
});
