import { expect, test } from '@playwright/test';

test('ordinary production game cannot expose debug controls and follows real time', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?debug=true&mode=qa');
  await page.getByRole('button', { name: 'How to Play', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('10% of successful sales replenishes Upgrade Funds');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'How to Play', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Start Game' }).click();
  await expect(page.locator('[data-renderer="ready"]')).toHaveCount(1);
  await expect(page.getByText('Developer inspector', { exact: false })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Step one tick' })).toHaveCount(0);
  await expect(page.getByTestId('diagnostics')).toHaveCount(0);
  await expect(page.locator('[data-frames],[data-nodes],[data-effects]')).toHaveCount(0);
  for (const name of ['Start operation', 'Connect resources', 'Build & connections', 'Save architecture']) await expect(page.getByRole('button', { name, exact: true })).toHaveCount(0);
  await expect(page.getByTestId('traffic')).toContainText('100', { timeout: 20000 });
  await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click(); await page.getByRole('button', { name: 'Inspect paused world', exact: true }).click();
  const paused = await page.getByTestId('budget').textContent();
  await page.waitForTimeout(1200); expect(await page.getByTestId('budget').textContent()).toBe(paused);
  await page.getByRole('button', { name: '▶ Resume', exact: true }).click();
  await page.getByRole('button', { name: 'Traffic intake', exact: true }).focus(); await page.getByRole('button', { name: 'Traffic intake', exact: true }).press('Enter');
  await page.getByRole('button', { name: 'Limit intake', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Resource actions' })).toContainText('Intake limited', { timeout: 10000 });
  await page.getByRole('button', { name: 'Close resource', exact: true }).click();
  await page.getByRole('button', { name: 'ⓘ Learn', exact: true }).click();
  await page.getByRole('button', { name: 'Return to title / restart', exact: true }).click();
  await page.getByRole('button', { name: 'Start Game' }).click();
  await expect(page.getByRole('region', { name: 'Business result' })).toContainText('Business interrupted', { timeout: 70000 });
  await expect(page.getByRole('region', { name: 'Business result' })).toContainText('Score 810');
  await page.screenshot({ path: info.outputPath('player-result.png') });
  await page.getByRole('button', { name: 'Play again', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Start Game' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('ordinary player builds live infrastructure through world controls without diagnostics', async ({ page }) => {
  await page.goto('/?tycoon&debug=true');
  await page.getByRole('button', { name: 'Start Game' }).click();
  await expect(page.locator('[data-renderer="ready"]')).toHaveCount(1, { timeout: 20000 });
  await expect(page.getByRole('button', { name: 'Ⅱ Pause', exact: true })).toBeEnabled({ timeout: 20000 });
  await page.getByRole('button', { name: /Deploy Cache — reduces SQL reads/ }).focus(); await page.getByRole('button', { name: /Deploy Cache — reduces SQL reads/ }).press('Enter');
  await expect(page.getByRole('button', { name: 'Confirm expansion', exact: true })).toHaveCount(0);
  { await page.getByRole('button', { name: /Deploy Protected Edge — filters bots/ }).focus(); await page.getByRole('button', { name: /Deploy Protected Edge — filters bots/ }).press('Enter'); };
  await expect(page.getByRole('button', { name: 'Confirm expansion', exact: true })).toHaveCount(0);
  { await page.getByRole('button', { name: /App capacity/ }).focus(); await page.getByRole('button', { name: /App capacity/ }).press('Enter'); };
  await expect(page.getByRole('button', { name: 'Confirm expansion', exact: true })).toHaveCount(0);
  await expect(page.getByTestId('slot-cache')).toContainText('Provisioning', { timeout: 5000 });
  await expect(page.getByTestId('slot-cache')).toContainText('Active', { timeout: 10000 });
  await expect(page.getByTestId('slot-edge')).toContainText('Active');
  await expect(page.getByRole('button', { name: /App capacity/ })).toContainText('2/4 active', { timeout: 10000 });
  await page.getByTestId('slot-edge').getByRole('button').focus(); await page.getByTestId('slot-edge').getByRole('button').press('Enter');
  await page.getByRole('button', { name: 'Boost filtering · $8K', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Boost filtering · $8K', exact: true })).toBeDisabled();
  await expect(page.getByTestId('diagnostics')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Step one tick' })).toHaveCount(0);
});
