import { expect, test } from '@playwright/test';

test('title settings and pause menu reuse player preferences without advancing the operation', async ({ page }, info) => {
  await page.goto('/');
  const settings = page.getByRole('button', { name: 'Settings', exact: true });
  await settings.click();
  const dialog = page.getByRole('dialog', { name: 'Settings', exact: true });
  await expect(dialog).toBeVisible();
  const centered = (await dialog.boundingBox())!;
  expect(Math.abs(centered.x + centered.width / 2 - page.viewportSize()!.width / 2)).toBeLessThan(2);
  await expect(dialog.getByRole('button', { name: 'Close settings' })).toBeFocused();
  await dialog.getByRole('checkbox', { name: 'Show gameplay tips' }).uncheck();
  await dialog.getByRole('button', { name: 'Enable sound', exact: true }).click();
  await dialog.getByRole('slider', { name: 'Volume' }).fill('0.35');
  await expect(dialog.getByRole('button', { name: 'Mute sound', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await dialog.getByRole('button', { name: 'Mute sound', exact: true }).click();
  await page.screenshot({ path: info.outputPath('settings-title.png') });
  await page.keyboard.press('Escape'); await expect(settings).toBeFocused();
  await page.getByRole('button', { name: 'Start Game', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Ⅱ Pause', exact: true })).toBeEnabled();
  await expect(page.getByRole('region', { name: 'World guide' })).toHaveCount(0);
  await page.keyboard.press('Escape');
  const pause = page.getByRole('dialog', { name: 'Paused', exact: true });
  await expect(pause).toBeVisible();
  await expect(pause.getByRole('button', { name: '▶ Resume', exact: true })).toBeFocused();
  const funds = await page.getByTestId('budget').textContent();
  const next = await page.getByTestId('next-wave').textContent();
  await page.waitForTimeout(1300);
  expect(await page.getByTestId('budget').textContent()).toBe(funds);
  expect(await page.getByTestId('next-wave').textContent()).toBe(next);
  await pause.getByRole('button', { name: 'Settings', exact: true }).click();
  await expect(dialog.getByRole('slider', { name: 'Volume' })).toHaveValue('0.35');
  await page.keyboard.press('Escape'); await expect(pause).toBeVisible();
  await pause.getByRole('button', { name: 'How to Play', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'How to Play', exact: true })).toBeVisible();
  await page.keyboard.press('Escape'); await expect(pause).toBeVisible();
  expect(await page.getByTestId('budget').textContent()).toBe(funds);
  await page.setViewportSize({ width: 844, height: 390 });
  await page.screenshot({ path: info.outputPath('pause-landscape.png') });
  const rect = (await pause.boundingBox())!;
  expect(Math.abs(rect.x + rect.width / 2 - 422)).toBeLessThan(2);
  expect(rect.x).toBeGreaterThanOrEqual(0); expect(rect.x + rect.width).toBeLessThanOrEqual(844);
  expect(rect.y).toBeGreaterThanOrEqual(0); expect(rect.y + rect.height).toBeLessThanOrEqual(390);
  await pause.getByRole('button', { name: 'Inspect paused world' }).click();
  await expect(pause).toHaveCount(0);
  await page.getByRole('button', { name: 'SQL processing', exact: true }).focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('region', { name: 'Resource actions' })).toBeVisible();
  await page.keyboard.press('Escape'); await expect(page.getByRole('region', { name: 'Resource actions' })).toHaveCount(0);
  await page.getByRole('button', { name: '▶ Resume', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Ⅱ Pause', exact: true })).toBeEnabled();
  await page.keyboard.press('Escape'); await expect(pause).toBeVisible();
  await page.keyboard.press('Escape'); await expect(pause).toHaveCount(0);
  await expect.poll(() => page.getByTestId('budget').textContent()).not.toBe(funds);
  await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click();
  await pause.getByRole('button', { name: 'Return to Title' }).click();
  await expect(page.getByRole('button', { name: 'Start Game', exact: true })).toBeFocused();
  await expect(page.locator('canvas')).toHaveCount(0);
});

test('rotation restores an open manual pause menu and renderer failure exposes recovery focus', async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Start Game', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Ⅱ Pause', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click();
  const pause = page.getByRole('dialog', { name: 'Paused', exact: true });
  await pause.getByRole('button', { name: 'Settings', exact: true }).click();
  const funds = await page.getByTestId('budget').textContent();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('dialog', { name: 'Landscape play required' })).toBeVisible();
  await page.setViewportSize({ width: 844, height: 390 });
  await page.getByRole('button', { name: 'Continue in landscape', exact: true }).click();
  await expect(pause).toBeVisible();
  await expect(pause.getByRole('button', { name: '▶ Resume', exact: true })).toBeFocused();
  await page.waitForTimeout(1200);
  expect(await page.getByTestId('budget').textContent()).toBe(funds);
  await pause.getByRole('button', { name: 'How to Play', exact: true }).click();
  await page.locator('canvas').evaluate(canvas => {
    const gl = (canvas as HTMLCanvasElement).getContext('webgl2') ?? (canvas as HTMLCanvasElement).getContext('webgl');
    const extension = gl?.getExtension('WEBGL_lose_context');
    if (!extension) throw new Error('Context loss extension unavailable');
    extension.loseContext();
  });
  const rebuild = page.getByRole('button', { name: 'Rebuild graphics', exact: true });
  await expect(rebuild).toBeFocused();
  await expect(page.getByRole('dialog', { name: 'How to Play', exact: true })).not.toBeVisible();
  expect(await page.getByTestId('budget').textContent()).toBe(funds);
  await rebuild.click();
  await expect(page.locator('[data-renderer="ready"]')).toHaveCount(1);
  await expect(page.locator('canvas')).toHaveCount(1);
});

test('fullscreen rejection and settings navigation are safe without starting gameplay', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(document, 'fullscreenEnabled', { value: true, configurable: true });
    Element.prototype.requestFullscreen = () => Promise.reject(new Error('Denied'));
  });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  const settings = page.getByRole('dialog', { name: 'Settings', exact: true });
  await settings.getByRole('button', { name: 'Enter fullscreen' }).click();
  await expect(settings).toContainText('Windowed landscape play still works');
  await settings.getByRole('button', { name: 'About / Credits' }).click();
  await expect(page.getByRole('dialog', { name: 'About Stack & Survive' })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.locator('canvas')).toHaveCount(0);
  await page.getByRole('button', { name: 'Start Game', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Landscape play required' })).toBeVisible();
});
