import { expect, test } from '@playwright/test';

for (const viewport of [{ width: 1440, height: 900 }, { width: 844, height: 390 }, { width: 667, height: 375 }]) {
  test(`world-local construction and event lifecycle at ${viewport.width}`, async ({ page }, info) => {
    await page.setViewportSize(viewport);
    await page.emulateMedia({ reducedMotion: viewport.width < 1000 ? 'reduce' : 'no-preference' });
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/');
    await page.getByRole('button', { name: 'Start Game', exact: true }).click();
    await expect(page.getByTestId('traffic')).toContainText('100');
    await expect(page.getByTestId('operation-banner')).toHaveCount(0);
    await page.getByRole('button', { name: 'Skip guide', exact: true }).click();
    const app = page.locator('[data-facility="compute"]');
    await expect(app.locator('strong')).toHaveText('APP');
    await expect(app).toContainText('Azure App Service');
    await expect(app).toContainText('1/4 active');
    const expand = page.getByRole('button', { name: '+ App capacity', exact: true });
    await expand.focus(); await expand.press('Enter');
    await expect(app).toContainText('EXPANDING');
    await expect(app).toContainText('1/4 active');
    await expect(app.locator('.facility-build-track')).toBeVisible();
    await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click();
    await page.getByRole('button', { name: 'Inspect paused world', exact: true }).click();
    const pending = await app.textContent();
    const funds = await page.getByTestId('budget').innerText();
    await page.waitForTimeout(1200);
    await expect(app).toHaveText(pending!);
    await expect(page.getByTestId('budget')).toHaveText(funds);
    await page.screenshot({ path: info.outputPath('construction-paused.png') });
    await page.getByRole('button', { name: '▶ Resume', exact: true }).click();
    await expect(app).toContainText('2/4 active', { timeout: 15000 });
    await expect(app.locator('.facility-build-track')).toHaveCount(0);
    const banner = page.getByTestId('operation-banner');
    await expect(banner).toContainText('APP READY');
    await page.screenshot({ path: info.outputPath('capacity-ready.png') });
    await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click();
    await expect(banner).toHaveCount(0);
    await page.getByRole('dialog', { name: 'Game paused' }).getByRole('button', { name: '▶ Resume', exact: true }).click();
    await expect(banner).toHaveCount(0);
    const cache = page.getByRole('button', { name: 'Deploy Cache — reduces SQL reads', exact: true });
    await cache.focus(); await cache.press('Enter');
    await expect(page.locator('[data-facility="cache"] .facility-build-track')).toBeVisible();
    await expect(page.locator('[data-facility="cache"] .facility-build-track')).toHaveCount(0, { timeout: 10000 });
    await expect(page.getByTestId('traffic')).toContainText('260', { timeout: 30000 });
    await expect(banner).toContainText('TRAFFIC SPIKE');
    await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).focus();
    const bounds = await banner.boundingBox();
    expect(bounds).not.toBeNull();
    expect(bounds!.x).toBeGreaterThanOrEqual(0);
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width);
    expect(bounds!.y).toBeGreaterThanOrEqual(100);
    if (viewport.width < 1000) expect(await banner.evaluate(el => getComputedStyle(el).animationName)).toBe('none');
    await page.screenshot({ path: info.outputPath('wave.png') });
    await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click();
    await page.getByRole('button', { name: 'Inspect paused world', exact: true }).click();
    const heldClock = await page.getByTestId('mission-clock').innerText();
    const heldFunds = await page.getByTestId('budget').innerText();
    await page.waitForTimeout(1200);
    await expect(page.getByTestId('mission-clock')).toHaveText(heldClock);
    await expect(page.getByTestId('budget')).toHaveText(heldFunds);
    await expect(banner).toHaveCount(0);
    await page.getByRole('button', { name: '▶ Resume', exact: true }).click();
    await expect(banner).toHaveCount(0);
    await expect(page.getByTestId('mission-clock')).not.toHaveText(heldClock);
    const edge = page.getByRole('button', { name: 'Deploy Protected Edge — filters bots', exact: true });
    await edge.focus(); await edge.press('Enter');
    await expect(banner).toContainText('PROTECTION ONLINE', { timeout: 10000 });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole('dialog', { name: 'Landscape play required' })).toBeVisible();
    await expect(banner).toHaveCount(0);
    await page.setViewportSize(viewport);
    await page.getByRole('button', { name: 'Continue in landscape', exact: true }).click();
    await expect(banner).toHaveCount(0);
    await page.waitForTimeout(1800);
    await expect(banner).toHaveCount(0);
    expect(errors).toEqual([]);
  });
}
