import { expect, test } from '@playwright/test';
import { formatMoneyRate } from '../../apps/web/src/money';

test('next-wave anticipation, single-action construction and reinvestment form a complete run', async ({page},info)=>{
  test.setTimeout(360000);
  await page.setViewportSize({width:1440,height:900});
  await page.addInitScript(()=>{
    localStorage.setItem('stack-and-survive.history.v1','legacy-record-not-to-be-overwritten');
    localStorage.setItem('stack-and-survive.progress.v1','legacy-progress-not-to-be-overwritten');
  });
  await page.goto('/?tycoon');await page.getByRole('button',{name:'Start Game',exact:true}).click();
  await expect(page.getByRole('button',{name:'Ⅱ Pause',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Skip guide',exact:true}).click();
  await page.getByText('Tycoon QA',{exact:true}).click();
  const step=page.getByRole('button',{name:'Step one tick',exact:true});await step.click();
  const view=async()=>JSON.parse((await page.getByTestId('diagnostics').textContent())!);
  const time=async()=>Number(await page.getByTestId('elapsed').textContent());
  const advance=async(target:number)=>{while(await time()<target)await step.click();};
  const build=async(name:string)=>{const b=page.getByRole('button',{name,exact:true});await b.focus();await b.press('Enter');await expect(page.getByRole('button',{name:'Confirm expansion'})).toHaveCount(0);};
  await expect(page.getByRole('region',{name:'Business status'})).toContainText('Upgrade Funds');
  await advance(16);await build('+ App capacity');
  const queued=(await view()).queuedActions;expect(queued).toHaveLength(1);
  await build('+ App capacity');expect((await view()).queuedActions).toHaveLength(1);
  await expect(page.getByRole('status').filter({hasText:/already|pending|queued/i})).toBeVisible();
  await step.click();await build('Add Cache');
  await advance(20);await expect(page.getByTestId('next-wave')).toContainText('5s');
  await expect(page.getByTestId('next-wave')).toContainText('Traffic spike');
  await expect(page.getByTestId('next-wave')).toHaveClass(/imminent/);
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath('next-wave-1440.png')});
  await advance(25);await expect(page.getByTestId('lost-sales')).toHaveText('$0/s');
  await expect(page.getByTestId('next-wave')).toContainText('Recovery window');
  const economy=(await view()).state.economy;
  expect(economy.remainingBudget).toBeCloseTo(75+economy.revenue*.1-economy.infrastructureCost-economy.emergencyCost,9);
  await advance(57);await build('+ App capacity');await build('Add Protected Edge');
  await expect(page.getByTestId('next-wave')).toContainText('Bot attack');
  await advance(65);await expect(page.getByTestId('next-wave')).toContainText('200');
  await advance(120);
  const r=(await view()).snapshot.requests;
  const loss=(r.offered.browse-r.successful.browse)*.002+(r.offered.order-r.successful.order)*.05;
  await expect(page.getByTestId('lost-sales')).toHaveText(formatMoneyRate(loss));
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath('wave-response-1440.png')});
  await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click(); await page.getByRole('button', { name: 'Inspect paused world', exact: true }).click();
  const frozen=await page.getByTestId('next-wave').textContent();await page.waitForTimeout(1100);
  expect(await page.getByTestId('next-wave').textContent()).toBe(frozen);
  await page.setViewportSize({width:844,height:390});await page.screenshot({path:info.outputPath('wave-hud-844.png')});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.getByRole('button',{name:'▶ Resume',exact:true}).click();await step.click();
  await advance(155);await expect(page.getByTestId('next-wave')).toContainText('FINAL WAVE');
  await advance(180);await expect(page.getByTestId('challenge-outcome')).toContainText('met');
  const result=(await view()).result;expect(result.balanceVersion).toBe('0.3');expect(result.metrics.availability).toBeGreaterThan(.99);
  expect(await page.evaluate(()=>localStorage.getItem('stack-and-survive.history.v1'))).toBe('legacy-record-not-to-be-overwritten');
  expect(await page.evaluate(()=>localStorage.getItem('stack-and-survive.progress.v1'))).toBe('legacy-progress-not-to-be-overwritten');
  await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('stack-and-survive.history.balance-0.4.v1')??'null')?.runs[0]?.challenge.rulesVersion)).toBe('0.4');
});
