import { expect, test } from '@playwright/test';

test('zoomed camera survives resize pause and renderer recovery but resets on a fresh run', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/?tycoon');
  await page.getByRole('button', { name: 'Start Game', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Ⅱ Pause', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click();
  await page.getByRole('button', { name: 'Skip guide', exact: true }).click();
  const surface = page.locator('[data-renderer="ready"]');
  const zoom = page.getByRole('status', { name: 'Camera zoom' });
  const camera = async () => JSON.parse((await surface.getAttribute('data-player-camera'))!);
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await expect.poll(async () => (await camera()).userZoom).toBe(1.5);
  const beforePause = await camera();
  await page.getByRole('button', { name: '▶ Resume', exact: true }).click();
  await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click();
  expect(await camera()).toEqual(beforePause);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(zoom).toHaveText('150%');
  await expect.poll(async () => page.locator('canvas').evaluate(c => c.clientWidth)).toBeLessThan(400);
  await expect(surface).toHaveAttribute('data-reduced-motion', 'true');
  await page.getByRole('button', { name: 'SQL processing', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('region', { name: 'Resource actions' })).toContainText('Writes:');
  await page.locator('.player-camera-controls > details > summary').click();
  await page.getByRole('button', { name: 'Focus selected', exact: true }).click();
  await page.getByRole('button', { name: 'Close resource', exact: true }).click();
  await page.locator('.player-camera-controls > details > summary').click();
  const beforeRecovery = await camera();
  const tick = await surface.getAttribute('data-tick');
  await page.locator('canvas').evaluate(canvas => {
    const gl = (canvas as HTMLCanvasElement).getContext('webgl2') ?? (canvas as HTMLCanvasElement).getContext('webgl');
    const extension = gl?.getExtension('WEBGL_lose_context');
    if (!extension) throw new Error('Context-loss extension unavailable');
    extension.loseContext();
  });
  await expect(page.getByRole('button', { name: 'Rebuild graphics', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Rebuild graphics', exact: true }).click();
  await expect(surface).toHaveCount(1);
  await expect(page.locator('canvas')).toHaveCount(1);
  await expect.poll(camera).toEqual(beforeRecovery);
  await expect(surface).toHaveAttribute('data-tick', tick!);
  await expect(zoom).toHaveText('150%');
  await page.getByRole('button', { name: 'ⓘ Learn', exact: true }).click();
  await page.getByRole('button', { name: 'Return to title / restart', exact: true }).click();
  await page.getByRole('button', { name: 'Start Game', exact: true }).click();
  await expect(zoom).toHaveText('100%');
  await expect(page.getByRole('button', { name: 'Ⅱ Pause', exact: true })).toBeEnabled();
  await expect.poll(async () => (await camera()).userZoom).toBe(1);
});
