import { expect, test } from '@playwright/test';

test('working facilities animate only active capacity and keep static equivalents without replaying completion', async ({ page }) => {
  await page.goto('/?tycoon'); await page.getByRole('button', { name: 'Start Game', exact: true }).click();
  const surface = page.locator('[data-renderer="ready"]'); await expect(surface).toHaveCount(1);
  await expect(page.getByRole('button', { name: 'Ⅱ Pause', exact: true })).toBeEnabled({ timeout: 20000 });
  await page.getByText('Tycoon QA', { exact: true }).click();
  const step = page.getByRole('button', { name: 'Step one tick', exact: true }); await step.click();
  const activity = async () => JSON.parse((await surface.getAttribute('data-resource-activity'))!);
  const serverCount = async () => (await activity()).items.filter((item: { type: string }) => item.type === 'server-work').length;
  await expect.poll(serverCount).toBe(1);
  const first = (await activity()).pose.angle;
  await expect.poll(async () => (await activity()).pose.angle).not.toBe(first);
  await page.getByRole('button', { name: '+ App capacity', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm expansion', exact: true }).click(); await step.click();
  await expect.poll(serverCount).toBe(1);
  for (let i=0;i<8;i++) await step.click();
  await expect.poll(serverCount).toBe(2);
  await surface.scrollIntoViewIfNeeded();
  await expect.poll(async () => Number(await surface.getAttribute('data-drawn-completions'))).toBeGreaterThan(0);
  await expect(surface).toHaveAttribute('data-completions', '[]');
  const completions = await surface.getAttribute('data-drawn-completions');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(surface).toHaveAttribute('data-reduced-motion', 'true');
  await expect.poll(async () => (await activity()).pose.phase).toBe(.25);
  await expect.poll(serverCount).toBe(2);
  await page.getByRole('button', { name: 'Ⅱ Pause', exact: true }).click();
  await expect.poll(async () => (await activity()).items).toEqual([]);
  expect(await surface.getAttribute('data-drawn-completions')).toBe(completions);
  await page.getByRole('button', { name: '▶ Resume', exact: true }).click();
  await step.click();
  const frozenTick = await page.getByTestId('elapsed').textContent();
  const frame = Number(await surface.getAttribute('data-frames'));
  await expect.poll(async () => Number(await surface.getAttribute('data-frames'))).toBeGreaterThan(frame + 10);
  await expect(page.getByTestId('elapsed')).toHaveText(frozenTick!);
  await expect(surface).toHaveAttribute('data-drawn-completions', completions!);
  await expect(surface).toHaveAttribute('data-completions', '[]');
  await expect.poll(serverCount).toBe(2);
});
