import type { Architecture } from '@stack-and-survive/schema';
import { architectureLearnResources, azureLearn, bicepLearnUrl } from './azure-learn';
import './export-azure.css';

export function AzureLearnLinks({ architecture }: { architecture: Architecture }) {
  return <section className="azure-learn" aria-label="Microsoft Learn resources">
    <p className="report-kicker">Continue with Microsoft Learn</p>
    <p>Official documentation for your final architecture. These links are curated, not generated by AI; real Azure behavior differs from the simulation.</p>
    <ul>{architectureLearnResources(architecture).map(resource => <li key={resource}>
      <a href={azureLearn[resource].url} target="_blank" rel="noopener noreferrer">{resource} → {azureLearn[resource].title} <span>(opens in new tab)</span></a>
    </li>)}</ul>
    <a href={bicepLearnUrl} target="_blank" rel="noopener noreferrer">Learn Bicep infrastructure as code <span>(opens in new tab)</span></a>
  </section>;
}
