import { useEffect, useRef, useState } from 'react';
import type { Architecture } from '@stack-and-survive/schema';
import type { View } from './controller';
import type { RunSummary } from './run-history';
import { buildExportRequest, requestExport, copyToClipboard, downloadText, type ExportResponse } from './export-azure';
import './export-azure.css';
import { azureLearn } from './azure-learn';

export function ExportAzurePanel({ result, run, architecture }: { result: NonNullable<View['result']>; run: RunSummary; architecture: Architecture }) {
  const [state, setState] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle');
  const [response, setResponse] = useState<ExportResponse | null>(null);
  const [copyStatus, setCopyStatus] = useState('');
  const generation = useRef(0), busy = useRef(false);
  useEffect(() => { generation.current++; busy.current = false; setState('idle'); setResponse(null); setCopyStatus(''); return () => { generation.current++; }; }, [result, architecture]);
  async function generate() {
    if (busy.current) return;
    busy.current = true; const requestId = ++generation.current; setState('loading'); setCopyStatus('');
    let value: ExportResponse | null;
    try { value = await requestExport(buildExportRequest(result, run, architecture)); } catch { value = null; }
    if (requestId !== generation.current) return;
    busy.current = false; setResponse(value); setState(value ? 'ready' : 'error');
  }
  async function copy() {
    if (!response) return; const requestId = generation.current;
    const copied = await copyToClipboard(response.bicep);
    if (requestId === generation.current) setCopyStatus(copied ? 'Bicep copied.' : 'Copy unavailable. Select the code or download the file.');
  }
  return <section className="export-azure" aria-label="Export to Azure" aria-busy={state === 'loading'}>
    <p className="report-kicker">From game to infrastructure</p>
    {(state === 'idle' || state === 'loading' || state === 'error') && <>
      <button type="button" className="report-alternate" disabled={state === 'loading'} onClick={() => { void generate(); }}>{state === 'loading' ? 'Generating Bicep…' : state === 'error' ? 'Retry Export to Azure' : 'Export to Azure'}<span>Generate Bicep for this architecture →</span></button>
      <p>On request, this run's simulation numbers and architecture are sent to the optional API and Azure OpenAI. No player name is included.</p>
      {state === 'error' && <p role="status">Export unavailable right now.</p>}
    </>}
    {state === 'ready' && response && <>
      <h3>{response.title}</h3>
      <ul>{response.resources.map(resource => <li key={resource.gameResource}><strong>{resource.gameResource} → {resource.azureService} ({resource.sku})</strong><p>{resource.reason}</p>
        <a href={azureLearn[resource.gameResource].url} target="_blank" rel="noopener noreferrer">Microsoft Learn: {azureLearn[resource.gameResource].title} (opens in new tab)</a>
      </li>)}</ul>
      <details><summary>main.bicep</summary><pre tabIndex={0} aria-label="Bicep template"><code>{response.bicep}</code></pre></details>
      <details><summary>main.parameters.json</summary><pre tabIndex={0} aria-label="Bicep parameters"><code>{response.parametersJson}</code></pre></details>
      <div className="export-azure-actions">
        <button type="button" onClick={() => { void copy(); }}>Copy Bicep</button>
        <button type="button" onClick={() => downloadText('main.bicep', response.bicep)}>Download main.bicep</button>
        <button type="button" onClick={() => downloadText('main.parameters.json', response.parametersJson)}>Download main.parameters.json</button>
      </div>
      <output aria-live="polite">{copyStatus}</output>
      <h4>Review requirements</h4><ul>{response.caveats.map((caveat, index) => <li key={`${index}-${caveat}`}>{caveat}</li>)}</ul>
      <p className="export-azure-note">Generated by Azure OpenAI from this run's numbers. Game capacities and costs are not Azure specifications. Review before deploying; nothing was deployed.</p>
    </>}
  </section>;
}
